version: '3.8'

services:

  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    volumes:
      - ../../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../../frontend/build:/usr/share/nginx/html/
      - ../backend/backend_static:/var/html/backend_static/
      - ../backend/media:/var/html/media/

volumes:
  db_volume:
