# Generated by Django 4.1 on 2023-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="friendsrequest",
            name="users_friendsrequest_unique_relationships",
        ),
        migrations.RemoveConstraint(
            model_name="friendsrequest",
            name="users_friendsrequest_prevent_self_add",
        ),
        migrations.RenameField(
            model_name="friendsrequest",
            old_name="current_user",
            new_name="from_user",
        ),
        migrations.RenameField(
            model_name="friendsrequest",
            old_name="friend",
            new_name="to_user",
        ),
        migrations.AddConstraint(
            model_name="friendsrequest",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"),
                name="users_friendsrequest_unique_relationships",
            ),
        ),
        migrations.AddConstraint(
            model_name="friendsrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("from_user", models.F("to_user")), _negated=True),
                name="users_friendsrequest_prevent_self_add",
            ),
        ),
    ]
