# Generated by Django 4.1 on 2023-07-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_remove_friendsrequest_users_friendsrequest_unique_relationships_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                help_text="Введите ваш e-mail",
                max_length=254,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
