# Generated by Django 4.1 on 2023-07-12 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0002_remove_friendsrequest_users_friendsrequest_unique_relationships_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Укажите долготу",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180.1),
                    django.core.validators.MaxValueValidator(90.1),
                ],
                verbose_name="Долгота",
            ),
        ),
    ]
