# Generated by Django 4.1 on 2023-07-18 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20230718_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="status",
            field=models.ForeignKey(
                default=1,
                help_text="Укажите статус",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="statuses",
                to="users.status",
                verbose_name="Статус",
            ),
        ),
    ]
