# Generated by Django 4.1 on 2023-07-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("none_category", "Без категории"),
                            ("friends", "Друзья"),
                            ("family", "Семья"),
                        ],
                        help_text="Укажите категорию друга",
                        max_length=50,
                        unique=True,
                        verbose_name="Название категории",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="friendsrelationship",
            name="friend_category",
            field=models.ForeignKey(
                default=1,
                help_text="Выберите категорию друга",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="friend_category",
                to="users.friendscategory",
                verbose_name="Категория друга",
            ),
        ),
    ]
