# Generated by Django 4.1 on 2023-07-20 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_merge_20230718_1521"),
        ("users", "0005_alter_customuser_status"),
    ]

    operations = []
