# Generated by Django 4.1 on 2023-07-28 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20230720_2305'),
        ('users', '0006_merge_20230721_0005'),
    ]

    operations = [
    ]
