# Generated by Django 4.1 on 2023-08-06 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_friendsrelationship_friend_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название",
                        max_length=50,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_black_theme",
                    models.BooleanField(
                        default=False, verbose_name="Темная тема да/нет"
                    ),
                ),
                (
                    "not_visible_for_cats",
                    models.ManyToManyField(
                        help_text="Выберите категории",
                        related_name="visibility",
                        to="users.friendcategory",
                        verbose_name="Категории",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Текущий пользователь",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="friendsrelationship",
            name="friend_category",
            field=models.ForeignKey(
                default=1,
                help_text="Укажите категорию друга",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="users.friendcategory",
                verbose_name="Название категории",
            ),
        ),
    ]
